Lesson 13 Wrappers Home Work
Nataliilebedeva/tms-aqa-ui pull request #4
Opened 2021-07-22 10:29 UTC by Nataliilebedeva

2021-08-02 11:19 UTC, wildpioneer requested changes

2021-08-02 11:19 UTC, wildpioneer commented on src/main/java/elements/CheckBox.java
> +    public  void  click(){
1. Форматирование
2. Для чего тебе здесь открытый метод click - если состояние чекбокса ты меняешь через changeState?

2021-08-02 11:19 UTC, wildpioneer commented on src/main/java/elements/DropDownMenu.java
> +    public void selectByText(String optionName) {
Если optionName не соответствует ни одному из вариантов - лучше выбрасывать exception что такой опции нет в списке

2021-08-02 11:19 UTC, wildpioneer commented on src/main/java/elements/DropDownMenu.java
> +    public void selectByIndex(int index) {
Здесь не плохо добавить проверку, что index не выходит за рамки размерности массива - и если выходит, выбрасывать exception.

2021-08-02 11:19 UTC, wildpioneer commented on src/main/java/elements/DropDownMenuByOneButton.java
> +public class DropDownMenuByOneButton {
Не совсем уловил момент этих двух похожих классов. Они вроде как выполняют одинаковый функционал, и соответственно дублируют друг друга - различие только в конструкторе. Необходимо обсудить на лекции - потому как есть потенциальная архитектурная ошибка.

2021-08-08 20:02 UTC, Nataliilebedeva commented on src/main/java/elements/CheckBox.java
> +    public  void  click(){
исправлено

2021-08-08 20:02 UTC, Nataliilebedeva commented on src/main/java/elements/DropDownMenu.java
> +    public void selectByText(String optionName) {
исправлено

2021-08-08 20:02 UTC, Nataliilebedeva commented on src/main/java/elements/DropDownMenu.java
> +    public void selectByIndex(int index) {
исправлено

2021-08-08 20:02 UTC, Nataliilebedeva commented on src/main/java/elements/DropDownMenuByOneButton.java
> +public class DropDownMenuByOneButton {
оговорили на занятии

2022-11-08 16:29 UTC, merged